#!/bin/bash
if [ -d "/opt/mapc" ]; then
	echo "mapc is already installed, overwrite? This will overwrite /opt/mapc [Y/N]:"
	read YN
	if [ $YN == "y" -o $YN == "Y" ]; then
		rm -rf /opt/mapc
	else
		exit
	fi
fi
if [ -h "/usr/bin/mapc" ]; then
    set -x
	rm /usr/bin/mapc
    set +x
fi

echo "Executing..."
set -x

mkdir /opt/mapc
cp mapc.py /opt/mapc/mapc.py
cp mapc.sh /opt/mapc/mapc.sh
chmod +x /opt/mapc/mapc.sh
ln -s /opt/mapc/mapc.sh /usr/bin/mapc

